name: Issue Report
description: Describe a new Issue
title: "[Issue]: "
labels: ["Issue", "triage"]
assignees:
  - OfficierAzarov
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to describe your issue!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: Solution
    attributes:
      label: Propose a solution
      description: You may have an idea of what we can do to improve the platform or fix the issue.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true